version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MONGODB_URI=mongodb+srv://rajveer43:pSajp7kXhbKd1KYz@dev-cluster.78ajkfz.mongodb.net/?retryWrites=true&w=majority&appName=dev-cluster
    volumes:
      - .:/app
    networks:
      - socialpilot-network

volumes:
  mongodb_data:

networks:
  socialpilot-network:
    driver: bridge